/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/dior-2.glb --keepnames -o ./src/components/Dior2.tsx 
*/

import * as THREE from "three";
import React, { useEffect, type JSX } from "react";
import { useGLTF, PerspectiveCamera, useTexture } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useControls } from "leva";
import { RepeatWrapping } from "three";

type GLTFResult = GLTF & {
  nodes: {
    ["floor-ceiling"]: THREE.Mesh;
    Circle: THREE.Mesh;
    Bottle__0: THREE.Mesh;
    ["perfume-holder"]: THREE.Mesh;
    ["perfume-holder001"]: THREE.Mesh;
    ["perfume-holder002"]: THREE.Mesh;
    ["perfume-holder003"]: THREE.Mesh;
    ["perfume-holder004"]: THREE.Mesh;
    ["perfume-holder005"]: THREE.Mesh;
    ["perfume-holder006"]: THREE.Mesh;
    ["perfume-holder007"]: THREE.Mesh;
    ["perfume-holder008"]: THREE.Mesh;
    ["perfume-holder009"]: THREE.Mesh;
    ["perfume-holder010"]: THREE.Mesh;
    ["perfume-holder011"]: THREE.Mesh;
    ["perfume-holder012"]: THREE.Mesh;
    ["perfume-holder013"]: THREE.Mesh;
    ["perfume-holder014"]: THREE.Mesh;
    ["perfume-holder015"]: THREE.Mesh;
    ["perfume-holder016"]: THREE.Mesh;
    ["perfume-holder017"]: THREE.Mesh;
    ["perfume-holder018"]: THREE.Mesh;
    ["perfume-holder019"]: THREE.Mesh;
    ["perfume-holder020"]: THREE.Mesh;
    ["perfume-holder021"]: THREE.Mesh;
    ["perfume-holder022"]: THREE.Mesh;
    ["perfume-holder023"]: THREE.Mesh;
    ["perfume-holder024"]: THREE.Mesh;
    walls: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export function Dior2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/dior-2.glb",
  ) as unknown as GLTFResult;

  const [WallNormal, WallRoughness] = useTexture([
    "/wall-normal.png",
    "/wall-roughness.png",
  ]);

  useEffect(() => {
    [WallNormal, WallRoughness].forEach((Map) => {
      Map.wrapS = Map.wrapT = RepeatWrapping;
      Map.repeat.set(1, 1);
      Map.needsUpdate = true;
      Map.rotation = -Math.PI / 2
      Map.center.set(0.5, 0.5)
    });

    return () => {};
  }, [WallNormal, WallRoughness]);

  const { metalness, roughness } = useControls({
    metalness: {
      value: 0.4,
      min: 0,
      max: 1,
    },
    roughness: {
      value: 0.45,
      min: 0,
      max: 1,
    },
  });

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        name="Camera"
        makeDefault
        far={1000}
        near={0.1}
        fov={22.895}
        position={[5.802, 1.663, 0.313]}
        rotation={[-Math.PI / 2, 1.332, Math.PI / 2]}
      />
      <PerspectiveCamera
        name="Camera001"
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[6.645, 3.343, 0.282]}
        rotation={[-1.386, 1.495, 1.385]}
      />
      <mesh
        name="floor-ceiling"
        geometry={nodes["floor-ceiling"].geometry}
        position={[-1.333, 2.59, 0]}
      >
        <meshStandardMaterial
          color={0x060606}
          metalness={metalness}
          roughness={roughness}
          normalMap={WallNormal}
          roughnessMap={WallRoughness}
        />
      </mesh>
      <mesh
        name="Circle"
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[2.151, 0.439, 0]}
      />
      <mesh
        name="Bottle__0"
        geometry={nodes.Bottle__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[2.152, 1.038, -0.002]}
        scale={0.003}
      />
      <mesh
        name="perfume-holder"
        geometry={nodes["perfume-holder"].geometry}
        material={nodes["perfume-holder"].material}
        position={[-3.838, 4.178, 2.048]}
      />
      <mesh
        name="perfume-holder001"
        geometry={nodes["perfume-holder001"].geometry}
        material={nodes["perfume-holder001"].material}
        position={[-3.838, 4.178, 1.018]}
      />
      <mesh
        name="perfume-holder002"
        geometry={nodes["perfume-holder002"].geometry}
        material={nodes["perfume-holder002"].material}
        position={[-3.838, 4.178, -0.012]}
      />
      <mesh
        name="perfume-holder003"
        geometry={nodes["perfume-holder003"].geometry}
        material={nodes["perfume-holder003"].material}
        position={[-3.838, 4.178, -1.043]}
      />
      <mesh
        name="perfume-holder004"
        geometry={nodes["perfume-holder004"].geometry}
        material={nodes["perfume-holder004"].material}
        position={[-3.838, 4.178, -2.073]}
      />
      <mesh
        name="perfume-holder005"
        geometry={nodes["perfume-holder005"].geometry}
        material={nodes["perfume-holder005"].material}
        position={[-3.838, 3.35, 2.048]}
      />
      <mesh
        name="perfume-holder006"
        geometry={nodes["perfume-holder006"].geometry}
        material={nodes["perfume-holder006"].material}
        position={[-3.838, 3.35, 1.018]}
      />
      <mesh
        name="perfume-holder007"
        geometry={nodes["perfume-holder007"].geometry}
        material={nodes["perfume-holder007"].material}
        position={[-3.838, 3.35, -0.012]}
      />
      <mesh
        name="perfume-holder008"
        geometry={nodes["perfume-holder008"].geometry}
        material={nodes["perfume-holder008"].material}
        position={[-3.838, 3.35, -1.043]}
      />
      <mesh
        name="perfume-holder009"
        geometry={nodes["perfume-holder009"].geometry}
        material={nodes["perfume-holder009"].material}
        position={[-3.838, 3.35, -2.073]}
      />
      <mesh
        name="perfume-holder010"
        geometry={nodes["perfume-holder010"].geometry}
        material={nodes["perfume-holder010"].material}
        position={[-3.838, 2.521, 2.048]}
      />
      <mesh
        name="perfume-holder011"
        geometry={nodes["perfume-holder011"].geometry}
        material={nodes["perfume-holder011"].material}
        position={[-3.838, 2.521, 1.018]}
      />
      <mesh
        name="perfume-holder012"
        geometry={nodes["perfume-holder012"].geometry}
        material={nodes["perfume-holder012"].material}
        position={[-3.838, 2.521, -0.012]}
      />
      <mesh
        name="perfume-holder013"
        geometry={nodes["perfume-holder013"].geometry}
        material={nodes["perfume-holder013"].material}
        position={[-3.838, 2.521, -1.043]}
      />
      <mesh
        name="perfume-holder014"
        geometry={nodes["perfume-holder014"].geometry}
        material={nodes["perfume-holder014"].material}
        position={[-3.838, 2.521, -2.073]}
      />
      <mesh
        name="perfume-holder015"
        geometry={nodes["perfume-holder015"].geometry}
        material={nodes["perfume-holder015"].material}
        position={[-3.838, 1.692, 2.048]}
      />
      <mesh
        name="perfume-holder016"
        geometry={nodes["perfume-holder016"].geometry}
        material={nodes["perfume-holder016"].material}
        position={[-3.838, 1.692, 1.018]}
      />
      <mesh
        name="perfume-holder017"
        geometry={nodes["perfume-holder017"].geometry}
        material={nodes["perfume-holder017"].material}
        position={[-3.838, 1.692, -0.012]}
      />
      <mesh
        name="perfume-holder018"
        geometry={nodes["perfume-holder018"].geometry}
        material={nodes["perfume-holder018"].material}
        position={[-3.838, 1.692, -1.043]}
      />
      <mesh
        name="perfume-holder019"
        geometry={nodes["perfume-holder019"].geometry}
        material={nodes["perfume-holder019"].material}
        position={[-3.838, 1.692, -2.073]}
      />
      <mesh
        name="perfume-holder020"
        geometry={nodes["perfume-holder020"].geometry}
        material={nodes["perfume-holder020"].material}
        position={[-3.838, 0.863, 2.048]}
      />
      <mesh
        name="perfume-holder021"
        geometry={nodes["perfume-holder021"].geometry}
        material={nodes["perfume-holder021"].material}
        position={[-3.838, 0.863, 1.018]}
      />
      <mesh
        name="perfume-holder022"
        geometry={nodes["perfume-holder022"].geometry}
        material={nodes["perfume-holder022"].material}
        position={[-3.838, 0.863, -0.012]}
      />
      <mesh
        name="perfume-holder023"
        geometry={nodes["perfume-holder023"].geometry}
        material={nodes["perfume-holder023"].material}
        position={[-3.838, 0.863, -1.043]}
      />
      <mesh
        name="perfume-holder024"
        geometry={nodes["perfume-holder024"].geometry}
        material={nodes["perfume-holder024"].material}
        position={[-3.838, 0.863, -2.073]}
      />
      <mesh
        name="walls"
        geometry={nodes.walls.geometry}
        position={[-1.333, 2.59, 0]}
      >
        <meshStandardMaterial
          color={0x060606}
          metalness={metalness}
          roughness={roughness}
          normalMap={WallNormal}
          roughnessMap={WallRoughness}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/dior-2.glb");
