/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/dior-2.glb --keepnames -o ./src/components/Dior2.tsx 
*/

import * as THREE from 'three'
import { useEffect, useState, type JSX } from 'react'
import { useGLTF, PerspectiveCamera, useTexture } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useControls } from 'leva'
import { RepeatWrapping } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    ['floor-ceiling']: THREE.Mesh
    base: THREE.Mesh
    Bottle__0: THREE.Mesh
    walls: THREE.Mesh
    ['picture-border']: THREE.Mesh
    ['picture-border002']: THREE.Mesh
    ['picture-border003']: THREE.Mesh
    ['picture-border004']: THREE.Mesh
    ['picture-border001']: THREE.Mesh
    picture: THREE.Mesh
    picture001: THREE.Mesh
    picture002: THREE.Mesh
    picture003: THREE.Mesh
    picture004: THREE.Mesh
    ['perfume-holder']: THREE.Mesh
    ['perfume-holder001']: THREE.Mesh
    ['perfume-holder002']: THREE.Mesh
    ['perfume-holder003']: THREE.Mesh
    ['perfume-holder004']: THREE.Mesh
    ['perfume-holder005']: THREE.Mesh
    ['perfume-holder006']: THREE.Mesh
    ['perfume-holder007']: THREE.Mesh
    ['perfume-holder008']: THREE.Mesh
    ['perfume-holder009']: THREE.Mesh
    ['perfume-holder010']: THREE.Mesh
    ['perfume-holder011']: THREE.Mesh
    ['perfume-holder012']: THREE.Mesh
    ['perfume-holder013']: THREE.Mesh
    ['perfume-holder014']: THREE.Mesh
    ['perfume-holder015']: THREE.Mesh
    ['perfume-holder016']: THREE.Mesh
    ['perfume-holder017']: THREE.Mesh
    ['perfume-holder018']: THREE.Mesh
    ['perfume-holder019']: THREE.Mesh
    ['perfume-holder020']: THREE.Mesh
    ['perfume-holder021']: THREE.Mesh
    ['perfume-holder022']: THREE.Mesh
    ['perfume-holder023']: THREE.Mesh
    ['perfume-holder024']: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export function Dior2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/dior-2.glb') as unknown as GLTFResult

  const [BottlePosition, setBottlePosition] = useState<THREE.Vector3>(new THREE.Vector3(2.15,.66,0))

  // useEffect(() => {
    
  //   if(nodes['Bottle__0']) {
  //     const v = new THREE.Vector3();
  //     nodes['Bottle__0'].getWorldPosition(v)
  //     console.log(v)
  //     setBottlePosition(v)
  //   }
  
  //   return () => {
      
  //   }
  // }, [nodes])
  

  const [WallNormal, WallRoughness] = useTexture([
    '/wall-normal.png',
    '/wall-roughness.png',
  ])
  

  const [BaseDiffuse, BaseRoughness] = useTexture([
    '/textures/marble_108_basecolor.png',
    '/textures/marble_108_roughness.png',
  ])

  const [BaseDiffuse2, BaseRoughness2] = useTexture([
    '/textures/Marble006_1K-JPG_Color.jpg',
    '/textures/Marble006_1K-JPG_Roughness.jpg',
  ])

  useEffect(() => {
    [WallNormal, WallRoughness].forEach((map) => {
      map.wrapS = map.wrapT = RepeatWrapping
      map.repeat.set(4, 4)
      map.center.set(0.5, 0.5)  // fixed: was (4,4) which is wrong
      map.needsUpdate = true
    })
  }, [WallNormal, WallRoughness])

  useEffect(() => {
    [BaseDiffuse, BaseRoughness].forEach((map) => {
      map.wrapS = map.wrapT = RepeatWrapping
      map.repeat.set(1, 1)
      map.needsUpdate = true
    })
  }, [BaseDiffuse, BaseRoughness])

  const { metalness, roughness, normalScale } = useControls({
    metalness: { value: 0.76, min: 0, max: 1 },
    roughness: { value: 0.0, min: 0, max: 1 },
    normalScale: { value: 1.4, min: 0, max: 10 },
  })

  const base = useControls('Base', {
    color: { value: '#303030' },
    metalness: { value: .0, min: 0, max: 1 },
    roughness: { value: .72, min: 0, max: 1 },
  })

  const wallMaterial = (
    <meshStandardMaterial
      color={0x060606}
      metalness={metalness}
      roughness={roughness}
      normalMap={WallNormal}
      normalScale={[normalScale, normalScale]}
      roughnessMap={WallRoughness}
    />
  )
  const floornceilingMaterial = (
    <meshStandardMaterial
      color={'#161616'}
      map={BaseDiffuse}
      metalness={.65}
      roughness={.72}
      roughnessMap={BaseRoughness}
    />
  )
  const baseMaterial = (
    <meshStandardMaterial
      color={base.color}
      map={BaseDiffuse2}
      metalness={base.metalness}
      roughness={base.roughness}
      roughnessMap={BaseRoughness2}
    />
  )

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera name="camera_bottle" makeDefault far={1000} near={0.1} fov={22.895} position={[6.407, 2.967, 0.648]} rotation={[-1.519, 1.01, 1.51]} />
      <PerspectiveCamera name="camera_frames" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[8.818, 3.554, 0.026]} rotation={[-1.386, 1.495, 1.385]} />

      <pointLight 
      position={BottlePosition}
      color={'white'}
      intensity={100}
      decay={8}
      />

      <mesh name="floor-ceiling" geometry={nodes['floor-ceiling'].geometry} position={[-1.333, 2.59, 0]}>
        {floornceilingMaterial}
      </mesh>

      <mesh name="walls" geometry={nodes.walls.geometry} position={[-1.333, 2.59, 0]}>
        {wallMaterial}
      </mesh>

      <mesh name="base" geometry={nodes.base.geometry} position={[2.151, 0.439, 0]}>
        {baseMaterial}
      </mesh>

      <mesh name="Bottle__0" geometry={nodes.Bottle__0.geometry} material={materials['Scene_-_Root']} position={[2.152, 0.738, -0.002]} />

      <mesh name="picture-border" geometry={nodes['picture-border'].geometry} material={nodes['picture-border'].material} position={[-3.957, 4.028, 1.931]} />
      <mesh name="picture-border002" geometry={nodes['picture-border002'].geometry} material={nodes['picture-border002'].material} position={[-3.957, 4.028, -1.931]} />
      <mesh name="picture-border003" geometry={nodes['picture-border003'].geometry} material={nodes['picture-border003'].material} position={[-3.957, 1.151, 1.931]} />
      <mesh name="picture-border004" geometry={nodes['picture-border004'].geometry} material={nodes['picture-border004'].material} position={[-3.957, 1.151, -1.931]} />
      <mesh name="picture-border001" geometry={nodes['picture-border001'].geometry} material={nodes['picture-border001'].material} position={[-3.957, 2.877, 0]} />

      <mesh name="picture" geometry={nodes.picture.geometry} material={nodes.picture.material} position={[-3.957, 4.028, 1.931]} />
      <mesh name="picture001" geometry={nodes.picture001.geometry} material={nodes.picture001.material} position={[-3.957, 2.877, 0]} />
      <mesh name="picture002" geometry={nodes.picture002.geometry} material={nodes.picture002.material} position={[-3.957, 4.028, -1.931]} />
      <mesh name="picture003" geometry={nodes.picture003.geometry} material={nodes.picture003.material} position={[-3.957, 1.151, 1.931]} />
      <mesh name="picture004" geometry={nodes.picture004.geometry} material={nodes.picture004.material} position={[-3.957, 1.151, -1.931]} />

      <mesh name="perfume-holder" geometry={nodes['perfume-holder'].geometry} material={nodes['perfume-holder'].material} position={[-3.838, 4.178, 2.048]} />
      <mesh name="perfume-holder001" geometry={nodes['perfume-holder001'].geometry} material={nodes['perfume-holder001'].material} position={[-3.838, 4.178, 1.018]} />
      <mesh name="perfume-holder002" geometry={nodes['perfume-holder002'].geometry} material={nodes['perfume-holder002'].material} position={[-3.838, 4.178, -0.012]} />
      <mesh name="perfume-holder003" geometry={nodes['perfume-holder003'].geometry} material={nodes['perfume-holder003'].material} position={[-3.838, 4.178, -1.043]} />
      <mesh name="perfume-holder004" geometry={nodes['perfume-holder004'].geometry} material={nodes['perfume-holder004'].material} position={[-3.838, 4.178, -2.073]} />
      <mesh name="perfume-holder005" geometry={nodes['perfume-holder005'].geometry} material={nodes['perfume-holder005'].material} position={[-3.838, 3.35, 2.048]} />
      <mesh name="perfume-holder006" geometry={nodes['perfume-holder006'].geometry} material={nodes['perfume-holder006'].material} position={[-3.838, 3.35, 1.018]} />
      <mesh name="perfume-holder007" geometry={nodes['perfume-holder007'].geometry} material={nodes['perfume-holder007'].material} position={[-3.838, 3.35, -0.012]} />
      <mesh name="perfume-holder008" geometry={nodes['perfume-holder008'].geometry} material={nodes['perfume-holder008'].material} position={[-3.838, 3.35, -1.043]} />
      <mesh name="perfume-holder009" geometry={nodes['perfume-holder009'].geometry} material={nodes['perfume-holder009'].material} position={[-3.838, 3.35, -2.073]} />
      <mesh name="perfume-holder010" geometry={nodes['perfume-holder010'].geometry} material={nodes['perfume-holder010'].material} position={[-3.838, 2.521, 2.048]} />
      <mesh name="perfume-holder011" geometry={nodes['perfume-holder011'].geometry} material={nodes['perfume-holder011'].material} position={[-3.838, 2.521, 1.018]} />
      <mesh name="perfume-holder012" geometry={nodes['perfume-holder012'].geometry} material={nodes['perfume-holder012'].material} position={[-3.838, 2.521, -0.012]} />
      <mesh name="perfume-holder013" geometry={nodes['perfume-holder013'].geometry} material={nodes['perfume-holder013'].material} position={[-3.838, 2.521, -1.043]} />
      <mesh name="perfume-holder014" geometry={nodes['perfume-holder014'].geometry} material={nodes['perfume-holder014'].material} position={[-3.838, 2.521, -2.073]} />
      <mesh name="perfume-holder015" geometry={nodes['perfume-holder015'].geometry} material={nodes['perfume-holder015'].material} position={[-3.838, 1.692, 2.048]} />
      <mesh name="perfume-holder016" geometry={nodes['perfume-holder016'].geometry} material={nodes['perfume-holder016'].material} position={[-3.838, 1.692, 1.018]} />
      <mesh name="perfume-holder017" geometry={nodes['perfume-holder017'].geometry} material={nodes['perfume-holder017'].material} position={[-3.838, 1.692, -0.012]} />
      <mesh name="perfume-holder018" geometry={nodes['perfume-holder018'].geometry} material={nodes['perfume-holder018'].material} position={[-3.838, 1.692, -1.043]} />
      <mesh name="perfume-holder019" geometry={nodes['perfume-holder019'].geometry} material={nodes['perfume-holder019'].material} position={[-3.838, 1.692, -2.073]} />
      <mesh name="perfume-holder020" geometry={nodes['perfume-holder020'].geometry} material={nodes['perfume-holder020'].material} position={[-3.838, 0.863, 2.048]} />
      <mesh name="perfume-holder021" geometry={nodes['perfume-holder021'].geometry} material={nodes['perfume-holder021'].material} position={[-3.838, 0.863, 1.018]} />
      <mesh name="perfume-holder022" geometry={nodes['perfume-holder022'].geometry} material={nodes['perfume-holder022'].material} position={[-3.838, 0.863, -0.012]} />
      <mesh name="perfume-holder023" geometry={nodes['perfume-holder023'].geometry} material={nodes['perfume-holder023'].material} position={[-3.838, 0.863, -1.043]} />
      <mesh name="perfume-holder024" geometry={nodes['perfume-holder024'].geometry} material={nodes['perfume-holder024'].material} position={[-3.838, 0.863, -2.073]} />
    </group>
  )
}

useGLTF.preload('/models/dior-2.glb')