/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/diorscene.glb --keepnames -o ./src/components/DiorScene.tsx 
*/

// Call this once at app init or inside a useEffect
import * as THREE from "three";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { RectAreaLightUniformsLib, type GLTF } from "three-stdlib";
import { useEffect, type JSX } from "react";
RectAreaLightUniformsLib.init();

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Circle: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane002: THREE.Mesh;
    ["emmisive-side-plane"]: THREE.Mesh;
    Plane003: THREE.Mesh;
    ["emmisive-back-plane"]: THREE.Mesh;
    Text: THREE.Mesh;
  };
  materials: {};
};

export function DiroScene(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/diorscene.glb",
  ) as unknown as GLTFResult;

  useEffect(() => {
    
    console.log(nodes)
  
    return () => {
      
    }
  }, [nodes])
  

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        name="main-cam"
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[34.495, 10.424, 0]}
        rotation={[-Math.PI / 2, 1.35, Math.PI / 2]}
      />

      {/* Floor */}
      <mesh name="Plane" geometry={nodes.Plane.geometry} scale={9.424}>
        <meshStandardMaterial color="#c8c8c8" roughness={0.8} metalness={0.1} />
      </mesh>

      {/* Pedestal / circle base */}
      <mesh
        name="Circle"
        geometry={nodes.Circle.geometry}
        position={[24.866, 0, 0]}
        scale={[1.648, 1, 1.648]}
      >
        <meshStandardMaterial color="#e0dcd8" roughness={0.4} metalness={0.6} />
      </mesh>

      {/* Wall panel 1 */}
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} scale={9.424}>
        <meshStandardMaterial
          color="#d4d0cc"
          roughness={0.7}
          metalness={0.15}
        />
      </mesh>

      {/* Wall panel 2 */}
      <mesh
        name="Plane002"
        geometry={nodes.Plane002.geometry}
        position={[-57.042, 0, 0]}
      >
        <meshStandardMaterial
          color="#d4d0cc"
          roughness={0.7}
          metalness={0.15}
        />
      </mesh>

      {/* Emissive side plane */}
      <mesh
        name="emmisive-side-plane"
        geometry={nodes["emmisive-side-plane"].geometry}
        scale={9.424}
      >
        <meshPhysicalMaterial
          color="white"
          emissive="white"
          emissiveIntensity={4}
        />
      </mesh>

      {/* Actual light at the same position/size */}
      <rectAreaLight
        position={[0, 0, 0]} // match your plane's world position
        width={9.424} // match the plane's scale
        height={9.424}
        intensity={10}
        color="white"
        rotation={[0, 0, 0]} // face the same direction as the plane
      />

      {/* Ground plane / shadow catcher */}
      <mesh
        name="Plane003"
        geometry={nodes.Plane003.geometry}
        position={[0, -0.244, 0]}
        scale={9.424}
      >
        <meshStandardMaterial
          color="#b8b4b0"
          roughness={0.9}
          metalness={0.05}
        />
      </mesh>

      {/* Text */}
      <mesh
        name="Text"
        geometry={nodes.Text.geometry}
        position={[-30.79, 6.069, -0.226]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={2.352}
      >
        <meshStandardMaterial color="#1a1a1a" roughness={0.3} metalness={0.8} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/diorscene.glb");
